# Generated by Django 5.2.7 on 2025-10-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20251012_2145'),
    ]

    operations = [
    ]
