# Generated by Django 5.2.7 on 2025-10-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20251013_1040'),
    ]

    operations = [
    ]
