# Generated by Django 5.2.7 on 2025-10-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20251013_1050'),
    ]

    operations = [
    ]
