# Generated by Django 5.2.7 on 2025-12-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='payment_status',
        ),
    ]
