# Generated by Django 5.2.7 on 2025-10-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20251013_1059'),
    ]

    operations = [
    ]
