# Generated by Django 5.2.7 on 2025-10-13 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20251013_1103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='vendor',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_banners/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
