# Generated by Django 5.2.7 on 2025-12-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_product_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reseller_mrp_price',
        ),
    ]
