# Generated by Django 5.2.7 on 2025-10-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_vendor_banner_and_more'),
    ]

    operations = [
    ]
