# Generated by Django 5.2.7 on 2025-10-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20251013_1241'),
    ]

    operations = [
    ]
