# Generated by Django 5.2.7 on 2025-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_remove_product_delivery_charge_inside_dhaka'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge_inside_dhaka',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
