# Generated by Django 5.2.7 on 2025-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_auto_20251013_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='shop_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
