# Generated by Django 5.2.7 on 2025-12-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_product_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
