# Generated by Django 5.2.7 on 2025-12-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
