# Generated by Django 5.2.7 on 2025-12-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
