# Generated by Django 5.2.7 on 2025-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_remove_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
