# Generated by Django 5.2.7 on 2025-12-04 17:22

from django.db import migrations


def convert_tags_to_json(apps, schema_editor):
    Product = apps.get_model('vendors', 'Product')
    for product in Product.objects.all():
        if product.tags:
            # Assuming tags are comma-separated strings, split and strip
            tag_list = [tag.strip() for tag in product.tags.split(',') if tag.strip()]
            product.tags = tag_list
        else:
            product.tags = []
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_product_variant'),
    ]

    operations = [
        migrations.RunPython(convert_tags_to_json),
    ]
