# Generated by Django 5.2.7 on 2025-10-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='referrals', to='users.user'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='own_refercode',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='own_refercode',
        ),
    ]
