# Generated by Django 5.2.7 on 2025-10-08 13:09

from django.db import migrations


def update_null_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')
    users = User.objects.filter(email__isnull=True)
    for i, user in enumerate(users):
        user.email = f"{user.username}_{i}@temp.com"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userinfo_referred_by_alter_user_referred_by_and_more'),
    ]

    operations = [
        migrations.RunPython(update_null_emails),
    ]
