# Generated by Django 4.2.27 on 2026-02-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('order', 'Order'), ('referral', 'Referral'), ('wallet', 'Wallet'), ('membership', 'Membership')], default='system', max_length=32),
        ),
    ]
