# Generated by Django 4.2.27 on 2026-03-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label (e.g. for admin list)', max_length=120)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/')),
                ('link', models.URLField(blank=True, help_text='Where to go when user taps the slide', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
