# Generated by Django (initial migration for recharge app)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileRecharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operator", models.CharField(max_length=10)),
                ("number_type", models.CharField(max_length=10)),
                ("mobile_number", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("refid", models.CharField(db_index=True, max_length=64, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("received", "Received"), ("success", "Success"), ("failed", "Failed"), ("refunded", "Refunded")], default="pending", max_length=20)),
                ("trxid", models.CharField(blank=True, max_length=128)),
                ("api_status", models.CharField(blank=True, max_length=32)),
                ("api_recharge_status", models.CharField(blank=True, max_length=32)),
                ("api_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mobile_recharges", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
