/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#3c4a46',
        'on-tertiary-fixed': '#21005e',
        surface: '#faf8ff',
        'primary-fixed': '#62fae3',
        'on-tertiary-container': '#5538a2',
        'inverse-primary': '#3cddc7',
        background: '#faf8ff',
        'primary-fixed-dim': '#3cddc7',
        'surface-variant': '#dae2fd',
        'tertiary-fixed-dim': '#cebdff',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        secondary: '#a43073',
        'secondary-container': '#fc79bd',
        'on-error': '#ffffff',
        tertiary: '#674bb5',
        'surface-dim': '#d2d9f4',
        'outline-variant': '#bacac5',
        'on-primary-container': '#00574d',
        'secondary-fixed-dim': '#ffafd3',
        outline: '#6b7a76',
        'tertiary-container': '#c6b3ff',
        'surface-container': '#eaedff',
        error: '#ba1a1a',
        primary: '#006b5f',
        'on-secondary-fixed': '#3d0026',
        'on-error-container': '#93000a',
        'surface-container-high': '#e2e7ff',
        'tertiary-fixed': '#e8ddff',
        'surface-bright': '#faf8ff',
        'on-tertiary-fixed-variant': '#4f319c',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#2dd4bf',
        'on-primary-fixed-variant': '#005047',
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'inverse-surface': '#283044',
        'surface-container-highest': '#dae2fd',
        'on-primary-fixed': '#00201c',
        'on-surface': '#131b2e',
        'on-background': '#131b2e',
        'on-secondary-fixed-variant': '#85145a',
        'secondary-fixed': '#ffd8e7',
        'surface-tint': '#006b5f',
        'on-secondary-container': '#76014e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        xl: '80px',
        lg: '48px',
        md: '24px',
        base: '8px',
        'margin-desktop': '40px',
        xs: '4px',
        'margin-mobile': '16px',
        sm: '12px',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'title-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
