/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        outline: '#76777b',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#98d0d7',
        'inverse-surface': '#313030',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#707278',
        'on-tertiary-container': '#437b81',
        'surface-dim': '#dcd9d9',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#2d141c',
        'on-error-container': '#93000a',
        'tertiary-container': '#e9fdff',
        'secondary-fixed': '#ffd9e2',
        'surface-tint': '#5d5e64',
        'on-primary-fixed-variant': '#45474c',
        'inverse-primary': '#c5c6cd',
        'surface-bright': '#fcf9f8',
        'primary-fixed': '#e2e2e9',
        secondary: '#78555e',
        'error-container': '#ffdad6',
        tertiary: '#2d666d',
        'secondary-container': '#ffd1dc',
        'on-surface-variant': '#45474b',
        'on-surface': '#1c1b1b',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#191c20',
        'surface-container-highest': '#e5e2e1',
        'surface-container-low': '#f6f3f2',
        'primary-fixed-dim': '#c5c6cd',
        'outline-variant': '#c6c6cb',
        'on-secondary-fixed-variant': '#5e3e47',
        'secondary-fixed-dim': '#e7bbc6',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        'on-secondary-container': '#7a5761',
        error: '#ba1a1a',
        primary: '#5d5e64',
        'tertiary-fixed': '#b3ecf3',
        'surface-container-high': '#eae7e7',
        'surface-container': '#f0eded',
        'surface-variant': '#e5e2e1',
        'on-background': '#1c1b1b',
        'primary-container': '#f8f8ff',
        'on-tertiary-fixed-variant': '#0d4e54',
        'on-tertiary-fixed': '#002023',
        background: '#fcf9f8',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      fontFamily: {
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
