# Generated by Django 5.2.7 on 2025-12-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_product_color_product_size_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='member_status',
        ),
    ]
