# Generated by Django 5.2.7 on 2025-12-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendor_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='member_status',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
