# Generated by Django 5.2.7 on 2025-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_vendor_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
