# Generated by Django 5.2.7 on 2025-12-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_remove_product_reseller_mrp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reseller_mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
