# Generated by Django 5.2.7 on 2025-12-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_product_reseller_mrp_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_charge_inside_dhaka',
        ),
    ]
