# Generated by Django 5.2.7 on 2025-12-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_product_delivery_charge_inside_dhaka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_charge_outside_dhaka',
        ),
    ]
