# Generated by Django 5.2.7 on 2025-12-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_product_delivery_charge_outside_dhaka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
    ]
