# Generated by Django 5.2.7 on 2025-12-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
