# Generated by Django 4.2.27 on 2026-02-05 20:46

from django.db import migrations, models


def migrate_order_status(apps, schema_editor):
    Order = apps.get_model("vendors", "Order")
    mapping = {"pending": "placed", "processing": "packed", "delivered": "received"}
    for old, new in mapping.items():
        Order.objects.filter(order_status=old).update(order_status=new)


def reverse_migrate_order_status(apps, schema_editor):
    Order = apps.get_model("vendors", "Order")
    mapping = {"placed": "pending", "packed": "processing", "received": "delivered"}
    for new, old in mapping.items():
        Order.objects.filter(order_status=new).update(order_status=old)


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_order_orderitem_order_vendors_ord_order_n_83f55a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('ban', 'Ban')], default='active', max_length=20),
        ),
        migrations.RunPython(migrate_order_status, reverse_migrate_order_status),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipping', 'Shipping'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
