# Generated by Django 4.2.27 on 2026-02-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_order_status_and_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_at_placement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount reseller paid when placing (e.g. full total for wallet, delivery only for COD)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount due to be paid later (e.g. for COD: total - delivery)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('mobile_banking', 'Mobile Banking'), ('cash_on_delivery', 'Cash on Delivery')], default='wallet', max_length=20),
        ),
    ]
