# Generated by Django 5.2.7 on 2025-10-06 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251006_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='referred_by',
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='own_refercode',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
