# Generated by Django 5.2.7 on 2025-10-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_null_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='own_refercode',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
