# Generated by Django 4.2.27 on 2026-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRestrictionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, help_text='{"hold": ["wallet", "withdrawals"], "ban": ["wallet", "withdrawals", "shop", "profile_edit", "membership", "referrals"], "inactive": ["wallet", "withdrawals", "shop", "profile_edit", "membership", "referrals"]}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account restriction config',
                'verbose_name_plural': 'Account restriction configs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('ban', 'Ban'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
