# Generated by Django 6.0.1 on 2026-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_account_status_and_restriction_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrestrictionconfig',
            name='config',
            field=models.JSONField(default=dict, help_text='hold, ban, inactive: lists of restricted areas. unverified_restricted_areas: list. member_status_allowed_areas: {user, Basic, Standard, Smart, VVIP: list of allowed areas}.'),
        ),
    ]
