# Generated by Django 4.2.27 on 2026-02-17 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_withdrawalrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='wallets_wit_user_id_dfd6dc_idx',
            old_name='wallets_with_user_id_6c55f9_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='wallets_wit_status_724b07_idx',
            old_name='wallets_with_status_5a8aa0_idx',
        ),
        migrations.AddField(
            model_name='wallet',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet'),
        ),
    ]
