# Generated by Django 4.2.27 on 2026-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_marketplace_reserved_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='source',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('funds', 'Funds')], default='wallet', max_length=10),
        ),
    ]
