# Generated by Django 6.0.1 on 2026-03-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_add_withdrawal_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='source',
        ),
    ]
